include:
  - project: 'AnatomicJC/gitlab-ci-templates'
    file: '/docker-hub.yml'

stages:
  - publish

variables:
  DOCKER_IMAGE: anatomicjc/ansible-docker

docker-publish-2.9.12:
  extends: .docker-hub-publish
  variables:
    DOCKER_VERSION: 2.9.12
    DOCKER_LATEST_TAG: "true"
    DOCKER_BUILD_ARGS: --build-arg ANSIBLE_VERSION=2.9.12
